### ISSUE TITLE
The wear app is crashing in wear OS 2.7

### ISSUE THREAD

**Issue by qichuan** [klinker24/talon-for-twitter-android#124]
Tested in TicWatch Pro, running wear OS 2.7

See the crash log below

```
	14:48:36.465	AndroidRuntime	FATAL EXCEPTION: main
Process: com.klinker.android.twitter_l, PID: 17191
android.view.InflateException: Binary XML file line #27: Binary XML file line #27: Error inflating class android.support.wearable.view.CircledImageView
Caused by: android.view.InflateException: Binary XML file line #27: Error inflating class android.support.wearable.view.CircledImageView
Caused by: java.lang.reflect.InvocationTargetException
	at java.lang.reflect.Constructor.newInstance0(Native Method)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
	at android.view.LayoutInflater.createView(LayoutInflater.java:647)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:790)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:730)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:863)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:824)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:515)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:423)
	at com.klinker.android.twitter_l.fragment.f.onCreateView(Unknown Source:4)
	at android.app.Fragment.performCreateView(Fragment.java:2522)
	at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1298)
	at android.app.FragmentManagerImpl.addAddedFragments(FragmentManager.java:2426)
	at android.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2205)
	at android.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2161)
	at android.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2062)
	at android.app.FragmentManagerImpl.executePendingTransactions(FragmentManager.java:818)
	at android.support.wearable.view.f.a(Unknown Source:23)
	at android.support.wearable.view.GridViewPager.f(Unknown Source:342)
	at android.support.wearable.view.GridViewPager.j(Unknown Source:6)
	at android.support.wearable.view.GridViewPager.onMeasure(Unknown Source:15)
	at android.view.View.measure(View.java:23169)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6749)
	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1535)
	at android.widget.LinearLayout.measureVertical(LinearLayout.java:825)
	at android.widget.LinearLayout.onMeasure(LinearLayout.java:704)
	at android.view.View.measure(View.java:23169)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6749)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
	at android.view.View.measure(View.java:23169)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6749)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
	at com.android.internal.policy.DecorView.onMeasure(DecorView.java:716)
	at android.view.View.measure(View.java:23169)
	at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:2735)
	at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1589)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1872)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1477)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7200)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:949)
	at android.view.Choreographer.doCallbacks(Choreographer.java:761)
	at android.view.Choreographer.doFrame(Choreographer.java:696)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:935)
	at android.os.Handler.handleCallback(Handler.java:873)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:193)
	at android.app.ActivityThread.main(ActivityThread.java:6680)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
Caused by: java.lang.UnsupportedOperationException: Can't convert value at index 3 to dimension: type=0x1c
	at android.content.res.TypedArray.getDimension(TypedArray.java:639)
```

**Comment by qichuan** [comment]
This crash can be fixed by replacing the deprecated `CircledImageView` with `CircularProgressLayout`.

The wear SDK is too old, I will create a PR to update it.
